### ISSUE TITLE
Melodic Release

### ISSUE THREAD

**Issue by dd-w** [frankaemika/libfranka-release#3]
Is it possible to release libfranka for Melodic? As it is the current LTS version of ROS.

**Comment by fwalch** [comment]
Yes, it should be possible to do a Melodic release. We have plans to do so in the near future.

**Comment by dd-w** [comment]
@fwalch great, thanks.

**Comment by fwalch** [comment]
As this is a duplicate of https://github.com/frankaemika/franka_ros/issues/34, I'm closing the issue here.
